model: "resnet18"

dataset:
  path: "/data_segments/threshold_100/"
  use_major_class: False

pipe:
  n_fft: 2048
  hop_length: 256
  sample_rate: 16000
  target_audio_sample_length: 16384
  n_mels: 40
  use_log: true
  min_audio_sample_length: 16384

training:
  batch_size: 48
  num_workers: 8
  max_epochs: 50
  log_every_n_steps: 5
  learning_rate: 0.001
  logdir: "/lightning_logs/threshold_100/"
